name: Restricted Branch Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-check:
    uses: udkyo/gha-test/.github/workflows/restricted-branch-check.yml@v1.0.0
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
