name: Restricted Branch Check

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  run-check:
    uses: udkyo/gha-test/.github/workflows/restricted-branch-check.yml@v1.0.0
    with:
      head_ref: ${{ github.event.pull_request.head.ref }}
      head_repo: ${{ github.event.pull_request.head.repo.full_name }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
